# Generated by Django 4.0.6 on 2022-08-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0009_autor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
